Homework2
made-ml-in-prod-2021/ekhusainov pull request #3
Opened 2021-05-14 00:55 UTC by ekhusainov

Первый раз работал с докером, пришлось немного помучиться, но было очень интересно. Все основные команды, необходимые для запусков оставил в README.md. Боюсь, что лишнего добавить и нечего. Разве что отмечу основное.
Оборачивание модели в rest-сервис:
python src\fastapi_app.py
Запуск 2-х запросов (один 200 и второй 400 HTTP):
python src\make_request.py
Сборка контейнера:
docker build -t xluttiy/ml_in_prod_hw02_ekh:v1 .
Его запуск:
docker run -p 8000:8000 xluttiy/ml_in_prod_hw02_ekh:v1

2021-05-17 09:07 UTC, LiahimRatman approved these changes
Всё хорошо, отличная работа, молодец)
С докера всё стянул, всё завелось как надо. Разве что можно get заменить на post

2021-05-17 09:07 UTC, LiahimRatman commented on online_inference/src/fastapi_app.py
> +    return make_predict(data, features)
Тут уместнее post-запрос

2021-05-17 09:07 UTC, LiahimRatman commented on online_inference/tests/test_fastapi.py
> +    answer_2 = check_request([{1: 2}])
Тут можно завернуть запросы в константы глобальные, например

2021-05-17 09:07 UTC, LiahimRatman commented on online_inference/src/fastapi_app.py
> +    if not check_request(request):
Что-то везде докстринги есть, а здесь потерялись)

2021-05-17 09:07 UTC, LiahimRatman commented on online_inference/src/fastapi_app.py
> +    return True
Я так понимаю, тут могут быть любые типы внутри dict? Тогда, теоретически, пользователь может вместо данных для фичей передавать туда текст и check_request на это ругаться не будет. Если сильнее запариваться, можно сделать валидацию типов внутри dict уже.

2021-05-18 10:51 UTC, ekhusainov commented on online_inference/src/fastapi_app.py
> +    return make_predict(data, features)
Поправил, хотя странно, что и так, и так работает)

2021-05-18 10:53 UTC, ekhusainov commented on online_inference/tests/test_fastapi.py
> +    answer_2 = check_request([{1: 2}])
done

2021-05-18 10:55 UTC, ekhusainov commented on online_inference/src/fastapi_app.py
> +    if not check_request(request):
done)

2021-05-18 11:27 UTC, ekhusainov commented on online_inference/src/fastapi_app.py
> +    return True
Добавил проверку на int и float)

2021-05-18 13:15 UTC, LiahimRatman approved these changes
Всё ок, отлично)

2021-05-22 17:10 UTC, Mikhail-M requested changes
Каждый раз, чтобы сделать предсказание модель прогружается, делает предсказание и выгружается.  Это критическая недоработка, сделайте, чтобы модель прогружалась при старте сервера

2021-05-23 14:03 UTC, ekhusainov commented
> 
> 
> Каждый раз, чтобы сделать предсказание модель прогружается, делает предсказание и выгружается. Это критическая недоработка, сделайте, чтобы модель прогружалась при старте сервера

Сделал)

2021-05-24 07:44 UTC, Mikhail-M requested changes
Удалите весь неиспользуемый код, актуализируйте работу после перехода на онлайн режим

2021-05-24 14:15 UTC, ekhusainov commented
> 
> 
> Удалите весь неиспользуемый код, актуализируйте работу после перехода на онлайн режим

снёс кучу кода, сократил количество модулей, перезалил docker

Ещё раз пожалел, что не писал через sklearn-овские пайплайны 1-е дз)

2021-05-26 10:43 UTC, Mikhail-M approved these changes
Баллы: думаю суммарно где-то 16, не буду расписывать по критериям.
Видно, что рефакторинг действительно перепроведен , но все еще видел непонятно зачем нужный код в batch_predict и закомментированный код 

В тестах желательно мокать модель или готовить ее в фикстаре.

в валидации сделать больше проверок и красиво юзается  https://pydantic-docs.helpmanual.io/usage/validators/

2021-05-30 15:34 UTC, merged